# Generated by Django 2.2 on 2019-04-03 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='car',
            name='manufacturer',
            field=models.CharField(max_length=50, verbose_name='Manufacturer'),
        ),
    ]
