# Generated by Django 2.2 on 2019-04-03 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190403_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='cost',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='car',
            name='issue_year',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1990)], verbose_name='Year of issue'),
        ),
        migrations.AlterField(
            model_name='car',
            name='manufacturer',
            field=models.CharField(max_length=50, null=True, verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Mileage'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=30, null=True, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='car',
            name='registration_number',
            field=models.PositiveIntegerField(null=True, verbose_name='Registration number'),
        ),
    ]
