# Generated by Django 2.2 on 2019-04-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190403_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(max_length=30, null=True, verbose_name="fuel's type"),
        ),
    ]
